### ISSUE TITLE
Create a PyPI package?

### ISSUE THREAD

**Issue by cjbassi** [brmscheiner/memorize.py#6]
I like this project and I think it would be nice to have it on PyPI so it's easier to install. I can submit a pr if you need me to.

**Comment by brmscheiner** [comment]
@cjbassi Good idea, I would very much appreciate that! Thank you

**Comment by brmscheiner** [comment]
Done! Great PR, thanks for the help.

https://pypi.org/project/memorize.py

**Comment by cjbassi** [comment]
Np! Glad it worked :D
